package smartarbitrage.api.model

object CancelReason extends Enumeration{
  type CancelReason = Value
  val POST_ONLY,
  FORCE_LIQUIDATED,
  INVALIDORDERTYPE,
  INVALIDSIDE,
  INVALIDPRICE,
  INSUFFICIENTAVAILABLEFUNDS,
  SELFFILL,
  TOOMANYSMALLORDERS,
  MARKETSUSPENDED,
  MARKETINACTIVE,
  CLIENTORDERIDALREADYEXIST,
  CLIENTORDERIDTOOLONG,
  MAXPOSITIONVIOLATION,
  CANCELLED,
  FILLED,
  NOTFOUND,
  REQUIREDARGUMENTMISSING = Value
}
