package smartarbitrage.api.model

import smartarbitrage.api.model.OrderType.OrderType

/**
 * A limit order.
 *
 * @author Fabio G. Strozzi
 */
trait LimitOrder {
  /**
   * Quotation pair code (e.g. btcusd, btceur, ethusd, ecc.)
   *
   * @return Quotation code
   */
  def getQCode: String

  // OrderType contiene delle chiamata a xchange
  def getSide: OrderType

  def getQuantity: java.math.BigDecimal

  def getPrice: java.math.BigDecimal

  def isPostOnly: Boolean

  def getLeverage: Int

  /**
   * Currency code (e.g. btc, usd, eth, eur, ecc.) used to indicate collateral in margin order
   *
   * @return Currency code
   */
  def getCollateralCurrency: Option[String]

  /**
   * Correlation id is generated by Smart Arbitrage and used on order placement to check if order is successfully placed
   *
   * @return Correlation Id
   */
  def getCorrelationId: Option[String]

}
